name: Deploy Django Application to Staging

on:
  workflow_dispatch:
  push:
    branches: [ staging ]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yaml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Deploying Django application to STAGING..."
          # Add staging deployment commands here
