name: Test Django Application

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/
        run: |
          python manage.py migrate


      - name: Run tests
        run: |
          python manage.py test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/
